# Note: Parameters can be hardcoded directly in '.github/workflows/deploy-functions.yaml'
# if you do not need to vary them between your functions!
description: "This function refreshes stale datapoints"
owner: Quantafuel
cpu: 1.0
memory: 1.0
metadata:  # optional metadata mapping
  version: "1.0.0"
# Parameters that are usually not needed to pass (they have good default values):
env_vars: {"COGNITE_BASE_URL": "https://api.cognitedata.com",
  "COGNITE_PROJECT": "susana",
  "COGNITE_TOKEN_URL": "https://login.microsoftonline.com/92bce3bb-abfb-484b-b074-32e1a37f3631/oauth2/v2.0/token",
  }
cdf_cluster: api
cdf_project: susana
tenant_id: 92bce3bb-abfb-484b-b074-32e1a37f3631
