# Note: Parameters can be hardcoded directly in '.github/workflows/deploy-functions.yaml'
# if you do not need to vary them between your functions!
common_folder: common
description: "Create events for all reported production numbers in the weekly report/balance sheet"
owner: Quantafuel
cpu: 1.0
memory: 1.0
env_vars: {"COGNITE_BASE_URL": "https://api.cognitedata.com",
  "COGNITE_PROJECT": "susana",
  "COGNITE_TOKEN_URL": "https://login.microsoftonline.com/92bce3bb-abfb-484b-b074-32e1a37f3631/oauth2/v2.0/token",
  }
cdf_cluster: api
cdf_project: susana
tenant_id: 92bce3bb-abfb-484b-b074-32e1a37f3631
